# Generated by Django 5.2.18 on 2026-10-07 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_at', models.DateTimeField(db_index=True)),
                ('verdict', models.CharField(default='AC', max_length=32)),
                ('notes', models.TextField(blank=True, max_length=10000)),
                ('source', models.CharField(default='manual', max_length=16)),
                ('independent', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommendations.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-solved_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'problem'), name='one_solve_per_problem')],
            },
        ),
    ]
