# Generated by Django 5.2.18 on 2026-10-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=24)),
                ('problem_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('curated', models.BooleanField(default=False)),
                ('topics', models.ManyToManyField(related_name='problems', to='recommendations.topic')),
            ],
            options={
                'ordering': ['difficulty', 'title'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'problem_id'), name='unique_problem'), models.CheckConstraint(condition=models.Q(('difficulty__gte', 1), ('difficulty__lte', 5)), name='valid_difficulty')],
            },
        ),
    ]
