# Generated by Django 5.2.18 on 2026-10-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(db_index=True, max_length=24)),
                ('external_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('cancelled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_at'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'external_id'), name='unique_contest')],
            },
        ),
    ]
