# Generated by Django 5.2.18 on 2026-10-07 18:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('morning', 'Morning'), ('before', 'Two hours before')], max_length=12)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('headers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sending', 'sending'), ('sent', 'sent'), ('cancelled', 'cancelled'), ('uncertain', 'uncertain'), ('failed', 'failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('reminder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.reminderdelivery')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=24)),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='reminderdelivery',
            constraint=models.UniqueConstraint(fields=('user', 'contest', 'kind'), name='unique_reminder'),
        ),
        migrations.AddConstraint(
            model_name='reminderpreference',
            constraint=models.UniqueConstraint(fields=('user', 'platform'), name='unique_reminder_preference'),
        ),
    ]
